name: CI_BLACKDUCK_SADMAN
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Black Duck Full Scan
        if: ${{ github.event_name != 'pull_request' }}
        uses: synopsys-sig/synopsys-action@SIGINT-2008
        ### Use below configuration to set specific detect environment variables
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
        with:
          # synopsys_bridge_download_url: https://artifactory.internal.synopsys.com/artifactory/clops-local/clops.sig.synopsys.com/synopsys-bridge/2.5.13/synopsys-bridge-2.5.13-macosx.zip
          # blackduck_reports_sarif_create: true                    
          # blackduck_reports_sarif_file_path:
          # blackduck_reports_sarif_severities:
          # blackduck_reports_sarif_groupSCAIssues:
          blackduck_url: ${{ secrets.BLACKDUCK_URL }}
          blackduck_apiToken: ${{ secrets.BLACKDUCK_API_TOKEN }}
          # blackduck_scan_full: true
          ### Accepts Multiple Values
          # blackduck_scan_failure_severities: 'BLOCKER,CRITICAL'
          blackduck_search_depth: 2
          blackduck_args: '--detect.diagnostic=true'
          blackduck_config_path: '/Users/siyaram/Downloads/SynopsysTestConfig/application.properties'
          ### Uncomment below configuration to enable automatic fix pull request creation if vulnerabilities are reported
          # blackduck_fixpr_enabled: true
          # blackduck_fixpr_maxCount: 5
          # blackduck_fixpr_filter_severities: 'CRITICAL,HIGH'
          # blackduck_fixpr_useUpgradeGuidance: 'SHORT_TERM,LONG_TERM'
          github_token: ${{ secrets.GITHUB_TOKEN }} # Mandatory when blackduck_fixpr_enabled is set to 'true'
