name: CI-Coverity

# Controls when the workflow will run
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    #  runs-on: [ ubuntu-latest ]
    runs-on: [ ubuntu-latest ]
    # Use ubuntu-latest to run workflow on github hosted runner
    #  runs-on: [ ubuntu-latest ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Coverity Full Scan
        if: ${{ github.event_name != 'pull_request' }}
        # Use the action defined in this repository
        uses: synopsys-sig/synopsys-action@SIGINT-2008
        with:
          coverity_url: ${{ vars.COVERITY_URL }}
          coverity_user: ${{ secrets.COVERITY_USER }}
          coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
          # coverity_project_name: ${{ secrets.COVERITY_PROJECT_NAME }}
          # coverity_stream_name: ${{ secrets.COVERITY_STREAM_NAME }}
          # coverity_policy_view: ${{ secrets.COVERITY_POLICY_VIEW }}
          # coverity_repository_name: ${{ secrets.COVERITY_REPOSITORY_NAME }}
          # coverity_branch_name: ${{ secrets.COVERITY_BRANCH_NAME }}
          #coverity_local: true
          coverity_args: -c /Users/siyaram/Downloads/SynopsysTestConfig/coverity.yml -o capture.build.clean-command="mvn clean" -- mvn clean install
          coverity_build_command: mvn clean install
          coverity_clean_command: mvn clean
          coverity_config_path: /Users/siyaram/Downloads/SynopsysTestConfig/application.properties

          # Mandatory for windows hosted environment
          # coverity_install_directory: "/root"
          # synopsys_bridge_download_url: https://artifactory.internal.synopsys.com/artifactory/clops-local/clops.sig.synopsys.com/synopsys-bridge/latest/synopsys-bridge-macosx.zip
          ### Uncomment below configuration if Synopsys Bridge diagnostic files needs to be uploaded
